name: Build

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install dependencies
              run: sudo apt update && sudo apt install -y build-essential mingw-w64

            - name: Create build dir
              run: mkdir ./build

            - name: Build Linux
              run: gcc -msse4.1 ./src/findany.c -o ./build/findany -O3

            - name: Build Windows
              run: x86_64-w64-mingw32-gcc -msse4.1 ./src/findany.c -o ./build/findany -O3

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                path: ./build
