name: Test

on:
    workflow_run:
        workflows: [Build]
        types:
            - completed

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: build-artifact
                path: ./build
            - name: List files
              run: ls ./build
